GNOME - Use docs helper
NickvisionApps/Parabolic pull request #492
Opened 2023-07-29 23:02 UTC by fsobolev

2023-07-29 23:04 UTC, nlogozzo requested changes

2023-07-29 23:04 UTC, nlogozzo commented on NickvisionTubeConverter.GNOME/Helpers/Help.cs
> +            using var linguasStream = Assembly.GetCallingAssembly().GetManifestResourceStream("NickvisionTagger.GNOME.LINGUAS");
TubeConverter

2023-07-29 23:06 UTC, fsobolev commented on NickvisionTubeConverter.GNOME/Helpers/Help.cs
> +            using var linguasStream = Assembly.GetCallingAssembly().GetManifestResourceStream("NickvisionTagger.GNOME.LINGUAS");
I can't believe I missed this haha

2023-07-29 23:08 UTC, nlogozzo commented on NickvisionTubeConverter.GNOME/Helpers/Help.cs
> +            using var linguasStream = Assembly.GetCallingAssembly().GetManifestResourceStream("NickvisionTagger.GNOME.LINGUAS");
The copy and paste is strong 😅

2023-07-29 23:09 UTC, nlogozzo approved these changes

2023-07-29 23:09 UTC, merged

2023-07-30 23:49 UTC, nlogozzo commented
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.0-rc1